#let conf(doc) = [
  #set page(
    paper: "a4",
    margin: (
      x: 7%,
      y: 5%
    ),
    footer: context {
      let index = counter(page)
      if index.get() == index.final() [
        #align(right, [
          This CV is generated by #link("https://github.com/pngwna/cvMax")[#underline("cvMax")] project by #link("https://github.com/PngWnA")[#underline("PngWnA")].
        ])
      ]
    }
  )

  #set text(
    size: 10pt,
    font: "KoPubWorldBatang",
    weight: "medium"
  )

  #set par(
    leading: 1em,
  )

  #doc
]