name: Proof of Concept using Typst

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile-cv:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Install KoPubWorld fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-kopubworld
          fc-cache -fv

      - name: Create directory for artifacts
        run: mkdir -p ${{ github.workspace }}/artifacts

      - name: Compile CV
        run: |
          typst compile --root . exporter/typst/main.typ ${{ github.workspace }}/artifacts/PngWnA.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PngWnA.pdf
          path: ${{ github.workspace }}/artifacts/PngWnA.pdf
